/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 57
#define LARGE_STATE_COUNT 12
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_LPAREN = 2,
  anon_sym_RPAREN = 3,
  anon_sym_DOT = 4,
  anon_sym_COMMA = 5,
  sym_identifier = 6,
  sym_boolean = 7,
  sym_number = 8,
  anon_sym_DQUOTE = 9,
  aux_sym_string_token1 = 10,
  sym_escape_sequence = 11,
  anon_sym_LBRACK = 12,
  anon_sym_RBRACK = 13,
  anon_sym_COLON = 14,
  sym_source_file = 15,
  sym_expression = 16,
  sym_chain_expression = 17,
  sym_arg = 18,
  sym_arg_list = 19,
  sym_string = 20,
  sym_list = 21,
  sym_map = 22,
  sym_map_entry = 23,
  aux_sym_source_file_repeat1 = 24,
  aux_sym_chain_expression_repeat1 = 25,
  aux_sym_arg_list_repeat1 = 26,
  aux_sym_string_repeat1 = 27,
  aux_sym_map_repeat1 = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DOT] = ".",
  [anon_sym_COMMA] = ",",
  [sym_identifier] = "identifier",
  [sym_boolean] = "boolean",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COLON] = ":",
  [sym_source_file] = "source_file",
  [sym_expression] = "expression",
  [sym_chain_expression] = "chain_expression",
  [sym_arg] = "arg",
  [sym_arg_list] = "arg_list",
  [sym_string] = "string",
  [sym_list] = "list",
  [sym_map] = "map",
  [sym_map_entry] = "map_entry",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_chain_expression_repeat1] = "chain_expression_repeat1",
  [aux_sym_arg_list_repeat1] = "arg_list_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_map_repeat1] = "map_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_identifier] = sym_identifier,
  [sym_boolean] = sym_boolean,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_source_file] = sym_source_file,
  [sym_expression] = sym_expression,
  [sym_chain_expression] = sym_chain_expression,
  [sym_arg] = sym_arg,
  [sym_arg_list] = sym_arg_list,
  [sym_string] = sym_string,
  [sym_list] = sym_list,
  [sym_map] = sym_map,
  [sym_map_entry] = sym_map_entry,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_chain_expression_repeat1] = aux_sym_chain_expression_repeat1,
  [aux_sym_arg_list_repeat1] = aux_sym_arg_list_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_map_repeat1] = aux_sym_map_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_chain_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_list] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_map] = {
    .visible = true,
    .named = true,
  },
  [sym_map_entry] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_chain_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arg_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_map_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_command_identifier = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_command_identifier] = "command_identifier",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_command_identifier, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '"', 24,
        '#', 9,
        '(', 10,
        ')', 11,
        '*', 3,
        ',', 13,
        '-', 4,
        '.', 12,
        ':', 30,
        '[', 28,
        '\\', 6,
        ']', 29,
        'f', 14,
        't', 17,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '{' ||
          lookahead == '}') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(25);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(10);
      if (lookahead == ']') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '{' ||
          lookahead == '}') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 5:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 6:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_boolean);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_boolean] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(53),
    [sym_expression] = STATE(32),
    [sym_chain_expression] = STATE(32),
    [sym_arg] = STATE(45),
    [sym_string] = STATE(28),
    [sym_list] = STATE(28),
    [sym_map] = STATE(28),
    [aux_sym_source_file_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
    [sym_boolean] = ACTIONS(11),
    [sym_number] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
  },
  [STATE(2)] = {
    [sym_expression] = STATE(23),
    [sym_chain_expression] = STATE(23),
    [sym_arg] = STATE(45),
    [sym_string] = STATE(28),
    [sym_list] = STATE(23),
    [sym_map] = STATE(23),
    [aux_sym_chain_expression_repeat1] = STATE(47),
    [aux_sym_arg_list_repeat1] = STATE(4),
    [sym_comment] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(19),
    [anon_sym_DOT] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
    [sym_identifier] = ACTIONS(9),
    [sym_boolean] = ACTIONS(11),
    [sym_number] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(19),
  },
  [STATE(3)] = {
    [sym_expression] = STATE(23),
    [sym_chain_expression] = STATE(23),
    [sym_arg] = STATE(45),
    [sym_string] = STATE(28),
    [sym_list] = STATE(23),
    [sym_map] = STATE(23),
    [aux_sym_arg_list_repeat1] = STATE(3),
    [sym_comment] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(28),
    [anon_sym_RPAREN] = ACTIONS(31),
    [anon_sym_COMMA] = ACTIONS(33),
    [sym_identifier] = ACTIONS(36),
    [sym_boolean] = ACTIONS(39),
    [sym_number] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(42),
    [anon_sym_LBRACK] = ACTIONS(45),
    [anon_sym_RBRACK] = ACTIONS(31),
  },
  [STATE(4)] = {
    [sym_expression] = STATE(23),
    [sym_chain_expression] = STATE(23),
    [sym_arg] = STATE(45),
    [sym_string] = STATE(28),
    [sym_list] = STATE(23),
    [sym_map] = STATE(23),
    [aux_sym_arg_list_repeat1] = STATE(3),
    [sym_comment] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(48),
    [anon_sym_COMMA] = ACTIONS(50),
    [sym_identifier] = ACTIONS(9),
    [sym_boolean] = ACTIONS(11),
    [sym_number] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(48),
  },
  [STATE(5)] = {
    [sym_expression] = STATE(28),
    [sym_chain_expression] = STATE(28),
    [sym_arg] = STATE(2),
    [sym_arg_list] = STATE(50),
    [sym_string] = STATE(28),
    [sym_list] = STATE(28),
    [sym_map] = STATE(28),
    [sym_map_entry] = STATE(38),
    [sym_comment] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_identifier] = ACTIONS(52),
    [sym_boolean] = ACTIONS(11),
    [sym_number] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(54),
  },
  [STATE(6)] = {
    [sym_expression] = STATE(28),
    [sym_chain_expression] = STATE(28),
    [sym_arg] = STATE(2),
    [sym_arg_list] = STATE(52),
    [sym_string] = STATE(28),
    [sym_list] = STATE(28),
    [sym_map] = STATE(28),
    [sym_comment] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(56),
    [sym_identifier] = ACTIONS(9),
    [sym_boolean] = ACTIONS(11),
    [sym_number] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
  },
  [STATE(7)] = {
    [sym_expression] = STATE(28),
    [sym_chain_expression] = STATE(28),
    [sym_arg] = STATE(2),
    [sym_arg_list] = STATE(51),
    [sym_string] = STATE(28),
    [sym_list] = STATE(28),
    [sym_map] = STATE(28),
    [sym_comment] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(58),
    [sym_identifier] = ACTIONS(9),
    [sym_boolean] = ACTIONS(11),
    [sym_number] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
  },
  [STATE(8)] = {
    [sym_expression] = STATE(32),
    [sym_chain_expression] = STATE(32),
    [sym_arg] = STATE(45),
    [sym_string] = STATE(28),
    [sym_list] = STATE(28),
    [sym_map] = STATE(28),
    [aux_sym_source_file_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(60),
    [sym_comment] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
    [sym_boolean] = ACTIONS(11),
    [sym_number] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
  },
  [STATE(9)] = {
    [sym_expression] = STATE(28),
    [sym_chain_expression] = STATE(28),
    [sym_arg] = STATE(19),
    [sym_string] = STATE(28),
    [sym_list] = STATE(28),
    [sym_map] = STATE(28),
    [sym_comment] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(48),
    [sym_identifier] = ACTIONS(9),
    [sym_boolean] = ACTIONS(11),
    [sym_number] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(48),
  },
  [STATE(10)] = {
    [sym_expression] = STATE(28),
    [sym_chain_expression] = STATE(28),
    [sym_arg] = STATE(19),
    [sym_string] = STATE(28),
    [sym_list] = STATE(28),
    [sym_map] = STATE(28),
    [sym_comment] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(62),
    [sym_identifier] = ACTIONS(9),
    [sym_boolean] = ACTIONS(11),
    [sym_number] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(62),
  },
  [STATE(11)] = {
    [sym_expression] = STATE(32),
    [sym_chain_expression] = STATE(32),
    [sym_arg] = STATE(45),
    [sym_string] = STATE(28),
    [sym_list] = STATE(28),
    [sym_map] = STATE(28),
    [aux_sym_source_file_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(64),
    [sym_comment] = ACTIONS(66),
    [anon_sym_LPAREN] = ACTIONS(69),
    [sym_identifier] = ACTIONS(72),
    [sym_boolean] = ACTIONS(75),
    [sym_number] = ACTIONS(75),
    [anon_sym_DQUOTE] = ACTIONS(78),
    [anon_sym_LBRACK] = ACTIONS(81),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    STATE(33), 1,
      sym_arg,
    ACTIONS(11), 3,
      sym_comment,
      sym_boolean,
      sym_number,
    STATE(28), 5,
      sym_expression,
      sym_chain_expression,
      sym_string,
      sym_list,
      sym_map,
  [28] = 7,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    STATE(19), 1,
      sym_arg,
    ACTIONS(11), 3,
      sym_comment,
      sym_boolean,
      sym_number,
    STATE(28), 5,
      sym_expression,
      sym_chain_expression,
      sym_string,
      sym_list,
      sym_map,
  [56] = 2,
    ACTIONS(86), 1,
      sym_identifier,
    ACTIONS(84), 11,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_boolean,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [73] = 2,
    ACTIONS(90), 1,
      sym_identifier,
    ACTIONS(88), 11,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_boolean,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [90] = 2,
    ACTIONS(94), 1,
      sym_identifier,
    ACTIONS(92), 11,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_boolean,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [107] = 2,
    ACTIONS(98), 1,
      sym_identifier,
    ACTIONS(96), 11,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_boolean,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [124] = 2,
    ACTIONS(102), 1,
      sym_identifier,
    ACTIONS(100), 11,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_boolean,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [141] = 4,
    ACTIONS(21), 1,
      anon_sym_DOT,
    ACTIONS(104), 1,
      sym_identifier,
    STATE(47), 1,
      aux_sym_chain_expression_repeat1,
    ACTIONS(31), 9,
      sym_comment,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_boolean,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [162] = 2,
    ACTIONS(108), 1,
      sym_identifier,
    ACTIONS(106), 11,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_boolean,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [179] = 2,
    ACTIONS(112), 1,
      sym_identifier,
    ACTIONS(110), 10,
      sym_comment,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_boolean,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [195] = 2,
    ACTIONS(116), 1,
      sym_identifier,
    ACTIONS(114), 10,
      sym_comment,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_boolean,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [211] = 3,
    ACTIONS(120), 1,
      anon_sym_DOT,
    ACTIONS(122), 1,
      sym_identifier,
    ACTIONS(118), 9,
      sym_comment,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_boolean,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [229] = 4,
    ACTIONS(124), 1,
      anon_sym_LPAREN,
    ACTIONS(126), 1,
      sym_identifier,
    ACTIONS(128), 1,
      anon_sym_COLON,
    ACTIONS(120), 8,
      sym_comment,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_boolean,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [249] = 3,
    ACTIONS(124), 1,
      anon_sym_LPAREN,
    ACTIONS(126), 1,
      sym_identifier,
    ACTIONS(120), 9,
      sym_comment,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_boolean,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [267] = 2,
    ACTIONS(132), 1,
      sym_identifier,
    ACTIONS(130), 10,
      sym_comment,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_boolean,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [283] = 2,
    ACTIONS(136), 1,
      sym_identifier,
    ACTIONS(134), 10,
      sym_comment,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_boolean,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [299] = 2,
    ACTIONS(126), 1,
      sym_identifier,
    ACTIONS(120), 10,
      sym_comment,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_boolean,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [315] = 2,
    ACTIONS(140), 1,
      sym_identifier,
    ACTIONS(138), 10,
      sym_comment,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_boolean,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [331] = 2,
    ACTIONS(144), 1,
      sym_identifier,
    ACTIONS(142), 10,
      sym_comment,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_boolean,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [347] = 2,
    ACTIONS(148), 1,
      sym_identifier,
    ACTIONS(146), 10,
      sym_comment,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_COMMA,
      sym_boolean,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [363] = 3,
    ACTIONS(120), 1,
      anon_sym_DOT,
    ACTIONS(152), 1,
      sym_identifier,
    ACTIONS(150), 7,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_LPAREN,
      sym_boolean,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
  [379] = 3,
    ACTIONS(21), 1,
      anon_sym_DOT,
    STATE(47), 1,
      aux_sym_chain_expression_repeat1,
    ACTIONS(154), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [390] = 4,
    ACTIONS(156), 1,
      anon_sym_DQUOTE,
    ACTIONS(158), 1,
      aux_sym_string_token1,
    ACTIONS(161), 1,
      sym_escape_sequence,
    STATE(34), 1,
      aux_sym_string_repeat1,
  [403] = 4,
    ACTIONS(164), 1,
      anon_sym_DQUOTE,
    ACTIONS(166), 1,
      aux_sym_string_token1,
    ACTIONS(168), 1,
      sym_escape_sequence,
    STATE(34), 1,
      aux_sym_string_repeat1,
  [416] = 4,
    ACTIONS(170), 1,
      anon_sym_DQUOTE,
    ACTIONS(172), 1,
      aux_sym_string_token1,
    ACTIONS(174), 1,
      sym_escape_sequence,
    STATE(35), 1,
      aux_sym_string_repeat1,
  [429] = 3,
    ACTIONS(176), 1,
      anon_sym_COMMA,
    ACTIONS(179), 1,
      anon_sym_RBRACK,
    STATE(37), 1,
      aux_sym_map_repeat1,
  [439] = 3,
    ACTIONS(181), 1,
      anon_sym_COMMA,
    ACTIONS(183), 1,
      anon_sym_RBRACK,
    STATE(42), 1,
      aux_sym_map_repeat1,
  [449] = 3,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(185), 1,
      sym_identifier,
    STATE(15), 1,
      sym_expression,
  [459] = 3,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(185), 1,
      sym_identifier,
    STATE(18), 1,
      sym_expression,
  [469] = 3,
    ACTIONS(187), 1,
      sym_identifier,
    ACTIONS(189), 1,
      anon_sym_RBRACK,
    STATE(46), 1,
      sym_map_entry,
  [479] = 3,
    ACTIONS(189), 1,
      anon_sym_RBRACK,
    ACTIONS(191), 1,
      anon_sym_COMMA,
    STATE(37), 1,
      aux_sym_map_repeat1,
  [489] = 3,
    ACTIONS(187), 1,
      sym_identifier,
    ACTIONS(193), 1,
      anon_sym_RBRACK,
    STATE(46), 1,
      sym_map_entry,
  [499] = 2,
    ACTIONS(195), 1,
      anon_sym_DOT,
    STATE(44), 1,
      aux_sym_chain_expression_repeat1,
  [506] = 2,
    ACTIONS(21), 1,
      anon_sym_DOT,
    STATE(47), 1,
      aux_sym_chain_expression_repeat1,
  [513] = 1,
    ACTIONS(179), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [518] = 2,
    ACTIONS(198), 1,
      anon_sym_DOT,
    STATE(44), 1,
      aux_sym_chain_expression_repeat1,
  [525] = 2,
    ACTIONS(187), 1,
      sym_identifier,
    STATE(46), 1,
      sym_map_entry,
  [532] = 2,
    ACTIONS(124), 1,
      anon_sym_LPAREN,
    ACTIONS(200), 1,
      anon_sym_DOT,
  [539] = 1,
    ACTIONS(202), 1,
      anon_sym_RBRACK,
  [543] = 1,
    ACTIONS(204), 1,
      anon_sym_RPAREN,
  [547] = 1,
    ACTIONS(206), 1,
      anon_sym_RPAREN,
  [551] = 1,
    ACTIONS(208), 1,
      ts_builtin_sym_end,
  [555] = 1,
    ACTIONS(128), 1,
      anon_sym_COLON,
  [559] = 1,
    ACTIONS(210), 1,
      sym_identifier,
  [563] = 1,
    ACTIONS(200), 1,
      anon_sym_DOT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(12)] = 0,
  [SMALL_STATE(13)] = 28,
  [SMALL_STATE(14)] = 56,
  [SMALL_STATE(15)] = 73,
  [SMALL_STATE(16)] = 90,
  [SMALL_STATE(17)] = 107,
  [SMALL_STATE(18)] = 124,
  [SMALL_STATE(19)] = 141,
  [SMALL_STATE(20)] = 162,
  [SMALL_STATE(21)] = 179,
  [SMALL_STATE(22)] = 195,
  [SMALL_STATE(23)] = 211,
  [SMALL_STATE(24)] = 229,
  [SMALL_STATE(25)] = 249,
  [SMALL_STATE(26)] = 267,
  [SMALL_STATE(27)] = 283,
  [SMALL_STATE(28)] = 299,
  [SMALL_STATE(29)] = 315,
  [SMALL_STATE(30)] = 331,
  [SMALL_STATE(31)] = 347,
  [SMALL_STATE(32)] = 363,
  [SMALL_STATE(33)] = 379,
  [SMALL_STATE(34)] = 390,
  [SMALL_STATE(35)] = 403,
  [SMALL_STATE(36)] = 416,
  [SMALL_STATE(37)] = 429,
  [SMALL_STATE(38)] = 439,
  [SMALL_STATE(39)] = 449,
  [SMALL_STATE(40)] = 459,
  [SMALL_STATE(41)] = 469,
  [SMALL_STATE(42)] = 479,
  [SMALL_STATE(43)] = 489,
  [SMALL_STATE(44)] = 499,
  [SMALL_STATE(45)] = 506,
  [SMALL_STATE(46)] = 513,
  [SMALL_STATE(47)] = 518,
  [SMALL_STATE(48)] = 525,
  [SMALL_STATE(49)] = 532,
  [SMALL_STATE(50)] = 539,
  [SMALL_STATE(51)] = 543,
  [SMALL_STATE(52)] = 547,
  [SMALL_STATE(53)] = 551,
  [SMALL_STATE(54)] = 555,
  [SMALL_STATE(55)] = 559,
  [SMALL_STATE(56)] = 563,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_list, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arg_list_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arg_list_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arg_list_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arg_list_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arg_list_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arg_list_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arg_list_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arg_list_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_list, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_list, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 1),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3, 0, 1),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chain_expression, 4, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_chain_expression, 4, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chain_expression, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_chain_expression, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_arg_list_repeat1, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 4, 0, 1),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 4, 0, 1),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arg_list_repeat1, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_arg_list_repeat1, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg, 1, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 4, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 4, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 3, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 3, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 5, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 5, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_entry, 3, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [158] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [161] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [176] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [195] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chain_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_chain_expression_repeat1, 2, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [208] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_fsl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "fsl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
